package {{ .Package.Name }}

// Code generated by astgen DO NOT EDIT

{{ with .File }}
{{ range ( .Types.WithTag "map" ) }}
// Keys returns a new slice containing the set of map keys. The order is unspecified.
func (m {{ .Name }}) Keys() (keys []string) {
	for name := range m {
		keys = append(keys, name)
	}

	return
}
{{ end }}
{{ end }}
