package painkiller

// Code generated by astgen v1.0 with go1.11.2 DO NOT EDIT

import (
	"strconv"
)

// String returns string representation for this value
func (i Pill) String() string {
	switch i {

	case Aspirin:
		return "Aspirin"

	case Ibuprofen:
		return "Ibuprofen"

	case Paracetamol:
		return "Paracetamol"

	case Placebo:
		return "Placebo"

	default:
		return "Pill(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
