package query

// Code generated by astgen v1.0 with go1.11.2 DO NOT EDIT

// Dump returns the AST node and skip the nil
func (ast *ConstDecl) Dump() string {
	return astDump(ast.ValueSpec)
}

// Dump returns the AST node and skip the nil
func (ast *FuncDecl) Dump() string {
	return astDump(ast.FuncDecl)
}

// Dump returns the AST node and skip the nil
func (ast *GenDecl) Dump() string {
	return astDump(ast)
}

// Dump returns the AST node and skip the nil
func (ast *ImportDecl) Dump() string {
	return astDump(ast.ImportSpec)
}

// Dump returns the AST node and skip the nil
func (ast *InterfaceDef) Dump() string {
	return astDump(ast.InterfaceType)
}

// Dump returns the AST node and skip the nil
func (ast *StructDef) Dump() string {
	return astDump(ast.StructType)
}

// Dump returns the AST node and skip the nil
func (ast *TypeDecl) Dump() string {
	return astDump(ast.TypeSpec)
}

// Dump returns the AST node and skip the nil
func (ast *VarDecl) Dump() string {
	return astDump(ast.ValueSpec)
}
