package query

// Code generated by astgen v1.0 with go1.11.2 DO NOT EDIT

// Dump returns the AST node and skip the nil
func (ast *ArrayType) Dump() string {
	return astDump(ast)
}

// Dump returns the AST node and skip the nil
func (ast *ChanType) Dump() string {
	return astDump(ast)
}

// Dump returns the AST node and skip the nil
func (ast *Field) Dump() string {
	return astDump(ast)
}

// Dump returns the AST node and skip the nil
func (ast *FuncType) Dump() string {
	return astDump(ast)
}

// Dump returns the AST node and skip the nil
func (ast *ImportSpec) Dump() string {
	return astDump(ast)
}

// Dump returns the AST node and skip the nil
func (ast *InterfaceType) Dump() string {
	return astDump(ast)
}

// Dump returns the AST node and skip the nil
func (ast *Labeled) Dump() string {
	return astDump(ast)
}

// Dump returns the AST node and skip the nil
func (ast *MapType) Dump() string {
	return astDump(ast)
}

// Dump returns the AST node and skip the nil
func (ast *Method) Dump() string {
	return astDump(ast)
}

// Dump returns the AST node and skip the nil
func (ast *NamedField) Dump() string {
	return astDump(ast)
}

// Dump returns the AST node and skip the nil
func (ast *Signature) Dump() string {
	return astDump(ast)
}

// Dump returns the AST node and skip the nil
func (ast *StructType) Dump() string {
	return astDump(ast)
}

// Dump returns the AST node and skip the nil
func (ast *TypeSpec) Dump() string {
	return astDump(ast)
}

// Dump returns the AST node and skip the nil
func (ast *ValueSpec) Dump() string {
	return astDump(ast)
}
