package query

// Code generated by astgen v1.0 with go1.11.2 DO NOT EDIT

// WithTagValue returns items contains tag which match the key and value
func (m NamedFieldMap) WithTagValue(key, value string) NamedFieldMap {
	return m.Filter(func(_name string, item *NamedField) bool {
		v, found := item.Tags().Lookup(key)

		return found && v == value
	})
}

// WithTag returns items with the tag
func (m NamedFieldMap) WithTag(key string) NamedFieldMap {
	return m.Filter(func(_name string, item *NamedField) bool {
		return item.Tags().Contains(key)
	})
}

// WithTag returns items without the tag
func (m NamedFieldMap) WithoutTag(key string) NamedFieldMap {
	return m.Filter(func(_name string, item *NamedField) bool {
		return !item.Tags().Contains(key)
	})
}
